provider:
  local:
    model_path: ./models/qwen_2_5_1_5b
    device: auto

  openai:
    base_url: https://api.deepseek.com/
    model: deepseek-v4-flash
    api_key: null

  active: openai
  max_new_token: 512
  temperature: 0.0

dataset:
  apibank:
    path: ./data/API-Bank
    split: 
      type: train # test/train
      level: 2 # 1/2/3
      subset: api # api/response

  toolace:
    path: ./data/ToolACE
    split: all # smoke/all

  active: apibank
  with_raw_data: true
  random_samples: true

log_level: debug
conversation_style: multi # single/multi 所有内容压缩在同一轮对话/多轮对话 note: 只有支持对话格式的模型可以使用multi格式
tool_format: standard # standard/plain 分别对应openai标准格式, 纯文本格式(EvalSample中规定的格式)  note: 只有conversation_style为multi, 且模型支持工具调用格式时支持stantard格式
sample_limit: 5 # 最多加载多少样本
  
