provider:
  local:
    model_path: ./models/qwen_2_5_1_5b
    device: auto

  openai:
    base_url: https://api.deepseek.com/
    model: deepseek-v4-flash
    api_key: sk-ff253f1bdf344be7b7b24570f2ccb5c4

  active: local
  max_new_token: 512
  temperature: 0.0

dataset:
  apibank:
    path: ./data/API-Bank
    split:
      type: train
      level: 2
      subset: api

  toolace:
    path: ./data/ToolACE
    split: smoke

  active: apibank
  with_raw_data: true
  random_samples: true

log_level: debug
conversation_style: single
tool_format: plain
sample_limit: 1
